version: '3'

services:
  web:
    build: .
    command: ["gunicorn", "brewerybook.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: brewerybook
      POSTGRES_USER: m22
      POSTGRES_PASSWORD: m22

volumes:
  postgres_data:
